spring:
  jpa:
    hibernate:
#      ddl-auto: update
#      ddl-auto: create-drop
      ddl-auto: validate

    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_bd
    username: postgres
    password: toor123
  flyway:
    baseline-on-migrate: true